import { Storage } from '@google-cloud/storage'; import { BigQuery } from '@google-cloud/bigquery';
export const storage=new Storage(); export const bigquery=new BigQuery();
export const bucket=()=>storage.bucket(process.env.GCS_BUCKET || 'nelture-careers-cv-dev');
export function safeName(name:string){return name.replace(/[^\w.() -]/g,'_').replace(/\s+/g,'-');}
export async function signedPut(path:string,mime:string,size:number){return bucket().file(path).getSignedUrl({version:'v4',action:'write',expires:Date.now()+600000,contentType:mime});}
export async function signedRead(path:string){return bucket().file(path).getSignedUrl({version:'v4',action:'read',expires:Date.now()+900000});}
export async function saveApplicationData(path:string,data:Record<string,unknown>){await bucket().file(path).save(JSON.stringify(data),{resumable:false,contentType:'application/json',metadata:{cacheControl:'no-store'}});}
export async function validMagic(path:string,mime:string,size:number){const f=bucket().file(path);const [exists]=await f.exists();if(!exists)return false;const [meta]=await f.getMetadata();if(Number(meta.size)!==size)return false;const [buf]=await f.download({start:0,end:7});return mime==='application/pdf'?buf.subarray(0,5).toString()==='%PDF-':buf.subarray(0,4).toString()==='PK\x03\x04';}
function query(sql:string,params:Record<string,unknown>){if(sql.includes('${'))throw new Error('Unsafe query template');return bigquery.query({query:sql,params,location:'asia-south1'});}
export async function createApplication(row:Record<string,unknown>){return query(`INSERT \`${process.env.GCP_PROJECT}.careers.applications\` (application_id,submitted_at,status,full_name,email,whatsapp,country_of_residence,nationality,passport_valid,passport_expiry,willing_to_travel,preferred_postings,role,experience_years,highest_education,certifications,prism_ai_ready,prism_ai_experience,motivation,sample_url,consent_dpdp,consent_contact,source,utm,ip_hash,updated_at,cv_gcs_uri,cv_original_filename,cv_mime,cv_size_bytes) VALUES (@id,CURRENT_TIMESTAMP(),'pending_upload',@name,@email,@whatsapp,@residence,@nationality,TRUE,@expiry,TRUE,JSON_VALUE_ARRAY(@postings),@role,@experience,@education,ARRAY(SELECT AS STRUCT JSON_VALUE(c,'$.provider') AS provider,JSON_VALUE(c,'$.name') AS name,JSON_VALUE(c,'$.credential_id') AS credential_id,JSON_VALUE(c,'$.verify_url') AS verify_url,SAFE_CAST(JSON_VALUE(c,'$.expiry') AS DATE) AS expiry FROM UNNEST(JSON_QUERY_ARRAY(@certifications)) c),TRUE,@prism,@motivation,@sample,TRUE,TRUE,@source,PARSE_JSON(@utm),@ipHash,CURRENT_TIMESTAMP(),@uri,@filename,@mime,@size)`,{...row,postings:JSON.stringify(row.postings||[]),certifications:JSON.stringify(row.certifications||[]),utm:JSON.stringify(row.utm||{})});}
export async function completeApplication(id:string){return query(`UPDATE \`${process.env.GCP_PROJECT}.careers.applications\` SET status='submitted', submitted_at=CURRENT_TIMESTAMP(), updated_at=CURRENT_TIMESTAMP() WHERE application_id=@id AND status='pending_upload'`,{id});}
export async function event(id:string,event:string,actor:string,detail:object={}){return query(`INSERT \`${process.env.GCP_PROJECT}.careers.application_events\` (application_id,\`at\`,event,actor,detail) VALUES (@id,CURRENT_TIMESTAMP(),@event,@actor,PARSE_JSON(@detail))`,{id,event,actor,detail:JSON.stringify(detail)});}
export {query};
